lets try this

diff --git a/.github/workflows/align.yml b/.github/workflows/align.yml
--- a/.github/workflows/align.yml
+++ b/.github/workflows/align.yml
@@ -34,9 +34,6 @@ env:
 
 jobs:
   build:
-    defaults:
-      run:
-        shell: bash -l {0}
     name: linux64
     runs-on: ubuntu-latest
     steps:
@@ -54,7 +51,7 @@ jobs:
           environment-file: misc/harpyenv.yaml
           cache-environment: true
           post-cleanup: 'all'
-          log-level: debug
+          log-level: error
       - name: Install harpy
         run: |
           python3 -m pip install --upgrade build && python3 -m build
@@ -64,24 +61,42 @@ jobs:
 
       - name: align bwa
         id: alignbwa
-        uses: mathiasvr/command-output@v1
-        with:
-          run: |
-            mamba activate harpy
-            harpy align -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
+        run: harpy align -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
+        shell: micromamba-shell {0}
 
-      - name: check bwa
-        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
-        run: exit 1
+#      - name: check bwa
+#        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
+#        run: exit 1
 
       - name: align ema
         id: alignema
-        uses: mathiasvr/command-output@v1
-        with:
-          run: |
-            mamba activate harpy
-            harpy align --method ema --ema-bins 20 -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
+        run: harpy align --method ema --ema-bins 20 -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
+        shell: micromamba-shell {0}
 
-      - name: check ema
-        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
-        run: exit 1
+#      - name: check ema
+#        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
+#        run: exit 1
+#
+#        - name: align bwa
+#        id: alignbwa
+#        uses: mathiasvr/command-output@v1
+#        with:
+#          run: |
+#            mamba activate harpy
+#            harpy align -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
+#
+#      - name: check bwa
+#        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
+#        run: exit 1
+#
+#      - name: align ema
+#        id: alignema
+#        uses: mathiasvr/command-output@v1
+#        with:
+#          run: |
+#            mamba activate harpy
+#            harpy align --method ema --ema-bins 20 -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
+#
+#      - name: check ema
+#        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
+#        run: exit 1
